'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpaceInvaders3._0.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property explosion() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("explosion", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property fastinvader1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("fastinvader1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property force_close() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("force_close", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property invaderkilled() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("invaderkilled", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property shoot() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("shoot", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property sibullet1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sibullet1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sibullet11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sibullet11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sibullet2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sibullet2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sibullet21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sibullet21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property siguy1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("siguy1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property siguy11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("siguy11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property siguy2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("siguy2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property siguy21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("siguy21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property siguy3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("siguy3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property siguy31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("siguy31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property siyou() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("siyou", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property siyou1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("siyou1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spaceinvaders1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("spaceinvaders1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ufo_lowpitch() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ufo_lowpitch", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
